      - name: Install & Build Web App
        run: |
          mkdir -p dist
          cp index.html dist/index.html || true
          npm install --legacy-peer-deps || true
          npm run build || true
          
